#define LORA_FREQUENCY 434.0F
#define LORA_BANDWIDTH 125.0F
#define LORA_SPREADING_FACTOR 9U
#define LORA_CODING_RATE 7U
#define LORA_SYNC_WORD 18U
#define LORA_OUTPUT_POWER 10
#define LORA_PREAMBLE_LENGTH 8U
#define LORA_GAIN 0U